-- Privilegios

-- Privilegios sobre la cuenta 1

GRANT SELECT, UPDATE, INSERT, DELETE ON CLIENTE TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMPLEADO TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON PEDIDOSUCURSAL TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON PRODUCTOR TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON REALIZAPEDIDO TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON SUCURSAL TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON VENDE TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON VINO TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE3;

-- Privilegios sobre la cuenta 2

GRANT SELECT, UPDATE, INSERT, DELETE ON CLIENTE TO MEDIGAHE4, MEDIGAHE1, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMPLEADO TO MEDIGAHE4, MEDIGAHE1, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON PEDIDOSUCURSAL TO MEDIGAHE4, MEDIGAHE1, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON PRODUCTOR TO MEDIGAHE4, MEDIGAHE1, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON REALIZAPEDIDO TO MEDIGAHE4, MEDIGAHE1, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON SUCURSAL TO MEDIGAHE4, MEDIGAHE1, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON VENDE TO MEDIGAHE4, MEDIGAHE1, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON VINO TO MEDIGAHE4, MEDIGAHE1, MEDIGAHE3;

-- Privilegios sobre la cuenta 3

GRANT SELECT, UPDATE, INSERT, DELETE ON CLIENTE TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE1;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMPLEADO TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE1;
GRANT SELECT, UPDATE, INSERT, DELETE ON PEDIDOSUCURSAL TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE1;
GRANT SELECT, UPDATE, INSERT, DELETE ON PRODUCTOR TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE1;
GRANT SELECT, UPDATE, INSERT, DELETE ON REALIZAPEDIDO TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE1;
GRANT SELECT, UPDATE, INSERT, DELETE ON SUCURSAL TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE1;
GRANT SELECT, UPDATE, INSERT, DELETE ON VENDE TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE1;
GRANT SELECT, UPDATE, INSERT, DELETE ON VINO TO MEDIGAHE4, MEDIGAHE2, MEDIGAHE1;

-- Privilegios sobre la cuenta 4

GRANT SELECT, UPDATE, INSERT, DELETE ON CLIENTE TO MEDIGAHE1, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMPLEADO TO MEDIGAHE1, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON PEDIDOSUCURSAL TO MEDIGAHE1, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON PRODUCTOR TO MEDIGAHE1, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON REALIZAPEDIDO TO MEDIGAHE1, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON SUCURSAL TO MEDIGAHE1, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON VENDE TO MEDIGAHE1, MEDIGAHE2, MEDIGAHE3;
GRANT SELECT, UPDATE, INSERT, DELETE ON VINO TO MEDIGAHE1, MEDIGAHE2, MEDIGAHE3;